install:
  - set QTDIR=C:\Qt\5.5\msvc2013_64
  - set PATH=%PATH%;%QTDIR%\bin;
  
before_build:
  - mkdir build
  - cd build
  - cmake ..

project:
  - ALL_BUILD.vcxproj
  
platform:
  - x86
  - Any CPU

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true
 
