os: Visual Studio 2015
version: 1.0.0.{build}

clone_folder: c:\projects\gtest-runner

configuration:
  - Debug
  - Release
  
environment:
  matrix:
  - VS_GEN: Visual Studio 12 2013
    QTDIR: C:\Qt\5.6\msvc2013
    EXT: win32
  - VS_GEN: Visual Studio 12 2013 Win64
    QTDIR: C:\Qt\5.6\msvc2013_64
    EXT: win64
  global:
    PWD:
      secure: 9z2ZbAlRhD7hRqEYrmxNMg==
    
branches:
  except:
    - gh-pages
    - documentation

matrix:
  fast_finish: true
  
install:
  - set PATH=%PATH%;%QTDIR%\bin;"c:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\"
  
build_script:
  - md build
  - cd build
  - cmake -Wno-dev -G"%VS_GEN%" ..
  - cmake --build . --config %CONFIGURATION%
  - cmake --build . --target PACKAGE --config %CONFIGURATION%

artifacts:
  - path: build\$(configuration)\gtest-runner-$(appveyor_repo_tag_name)-$(EXT).exe
    name: windows_installer
  - path: build\$(configuration)\gtest-runner-$(appveyor_repo_tag_name)-$(EXT).zip
    name: windows_portable
    type: zip
  
before_deploy:
  - signtool.exe sign /f c:\projects\gtest-runner\resources\certificates\certum.pfx /p %PWD% C:\workspace\gtest-runner\build\%CONFIGURATION%\gtest-runner-%APPVEYOR_REPO_TAG_NAME%-%EXT%.exe
  
deploy:
  tag: $(appveyor_repo_tag_name)
  description: windows binaries
  provider: GitHub
  auth_token:
    secure: FtWS/a/Vb7xeJrcZYs+9AtDnQ3aNqfL56NnjMYFvwokdPUP4qo4BImfPFr4H67A6
  artifact: windows_installer,windows_portable
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    configuration: Release 
    appveyor_repo_tag: true        # deploy on tag push only
