os: Visual Studio 2015
version: 1.0.0.{build}

environment:
  matrix:
  - VS_GEN: Visual Studio 12 2013
    CONFIG: Debug
    QTDIR: C:\Qt\5.5\msvc2013
  - VS_GEN: Visual Studio 12 2013
    CONFIG: Release
    QTDIR: C:\Qt\5.5\msvc2013
  - VS_GEN: Visual Studio 12 2013 Win64
    CONFIG: Release
    QTDIR: C:\Qt\5.5\msvc2013_64
    
matrix:
  fast_finish: true
  
install:
  - set PATH=%PATH%;%QTDIR%\bin;
  
before_build:
  - md build
  - cd build
  - cmake -Wno-dev -G"%VS_GEN%" -DCMAKE_BUILD_TYPE=%CONFIG% ..
  - cd ..
  - dir
  
configuration:
  - Debug
  - Release
 
build:
  parallel: true
  project: build/gtest-runner-HEAD.sln

artifacts:
  - path: Release/gtest-runner-$(appveyor_repo_tag_name)-win64.exe
    name: installer
  - path: Release/gtest-runner-$(appveyor_repo_tag_name)-win64.zip
    name: zip_executable
    type: zip

before_deploy:
  - cd build
  - cpack -G NSIS -C Release
  - cpack -G ZIP -C Release
  - cd ..
  
deploy:
  release: Windows Installer - v$(appveyor_repo_tag_name)
  description: gtest-runner automated binary installer for windows
  provider: GitHub
  auth_token:
    secure: FtWS/a/Vb7xeJrcZYs+9AtDnQ3aNqfL56NnjMYFvwokdPUP4qo4BImfPFr4H67A6
  artifact: installer, zip_executable
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    configuration: Release 
    appveyor_repo_tag: true        # deploy on tag push only