os: Visual Studio 2013
version: 1.0.0.{build}

install:
  - set QTDIR=C:\Qt\5.5\msvc2013
  - set PATH=%PATH%;%QTDIR%\bin;
  
before_build:
  - md build
  - cd build
  - cmake ..
  - cd ..
  - dir
  
configuration:
  - Debug
  - Release
 
build:
  project: build/gtest-runner-$(appveyor_repo_branch).sln

deploy:
  release: Windows Installer - v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: FtWS/a/Vb7xeJrcZYs+9AtDnQ3aNqfL56NnjMYFvwokdPUP4qo4BImfPFr4H67A6
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only