install:
  - set QTDIR=C:\Qt\5.5\msvc2013
  - set PATH=%PATH%;%QTDIR%\bin;
  
before_build:
  - md build
  - cd build
  - cmake ..
  - cd ..
  - dir

platform:
  - x86
  
configuration:
  - Debug
#  - Release
 
build:
  project: build/gtest-gui-HEAD.sln
