install:
  - set QTDIR=C:\Qt\5.5\msvc2013_64
  - set PATH=%PATH%;%QTDIR%\bin;
  
before_build:
  - md build
  - cd build
  - cmake ..
  - cd ..
  - dir

#configuration:
#  - Debug
#  - Release

matrix:
  fast_finish: true
 
build:
  parallel: true
  project: build\gtest-gui-HEAD.sln
