install:
  - set QTDIR=C:\Qt\5.5\msvc2013_64
  - set PATH=%PATH%;%QTDIR%\bin;
  
before_build:
  - md build
  - cd build
  - cmake ..
  - dir
  
#platform:
#  - x86
#  - Any CPU

#configuration:
#  - Debug
#  - Release

matrix:
  fast_finish: true
 
build:
  parallel: true
  project: gtest-gui-HEAD.sln
